theme: jekyll-theme-minimal
title: Beers Across the Atlantic: Decoding Beer Preferences in North America and Europe
description: Webpage used for developing a story about the beer preferences in America and Europe
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
