theme: bulma-clean-theme
title: Beers Across the Atlantic
description: Decoding Beer Preferences in North America and Europe
show_downloads: false

# Plugins
plugins:
  # TODO: Enable this at the end.
  # - jemoji
  - jekyll-remote-theme

# Global theme settings
fixed_navbar: top
hide_footer: false
show_sidebar: false

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/