theme: jekyll-theme-minimal
title: Beers Across the Atlantic
description: Decoding Beer Preferences in North America and Europe
show_downloads: True
plugins:
  - jemoji
navigation:
  - title: Home
    url: /
  - title: Data sources
    url: Data sources.md
  - title: Naive analysis
    url: Naive analysis.md
  - title: Beer styles
    url: Beer styles.md
