theme: jekyll-theme-minimal
title: Beers Across the Atlantic
description: Decoding Beer Preferences in North America and Europe
show_downloads: false

# Plugins
plugins:
  - jemoji

# Navigation
navigation:
  - title: Home
    url: /
  - title: Data sources
    url: '/Data sources'
  - title: Naive analysis
    url: '/Naive analysis'
  - title: Seasonality analysis
    url: '/Seasonality analysis'
  - title: Beer styles
    url: '/Beer styles'
  - title: Time evolution
    url: '/Time evolution'
  - title: Seasonality
    url: '/Seasonality'

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/